#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


module ResultCode
  OK = 0
  TRY_LATER = 1
  VALUE_MAP = {0 => "OK", 1 => "TRY_LATER"}
  VALID_VALUES = Set.new([OK, TRY_LATER]).freeze
end

class Event
  include ::Thrift::Struct, ::Thrift::Struct_Union
  TIMESTAMP = 1
  CATEGORY = 2
  KEY = 3
  VALUE = 4

  FIELDS = {
    TIMESTAMP => {:type => ::Thrift::Types::I64, :name => 'timestamp'},
    CATEGORY => {:type => ::Thrift::Types::STRING, :name => 'category'},
    KEY => {:type => ::Thrift::Types::LIST, :name => 'key', :element => {:type => ::Thrift::Types::STRING}},
    VALUE => {:type => ::Thrift::Types::I64, :name => 'value'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

